version: '3.7'
services:
    mybodypix:
        image: mybodypix
        init: true
        build:
            context: ./bodypix
        networks:
            - fakecam
        read_only: true
        ports:
            - ${PORT_BODYPIX}:9000

    myfakecam:
        image: myfakecam
        init: true
        build:
            context: ./fakecam
        networks:
            - fakecam
        read_only: true
        volumes:
            - ${IMAGE_BACKGROUND}:/src/background-custom:ro
            - ${IMAGE_FOREGROUND}:/src/foreground-custom:ro
            - ${IMAGE_FOREGROUND_MASK}:/src/foreground-mask-custom:ro
        devices:
            - ${VIDEO_INPUT}:/dev/video0
            - ${VIDEO_OUTPUT}:/dev/video2
        depends_on:
            - mybodypix
        command: ["--bodypix-url", "http://mybodypix:9000/",
                  "-b", "background-custom", "-f", "foreground-custom" , "-m", "foreground-mask-custom",
                  "--webcam-path", "/dev/video0", "--v4l2loopback-path", "/dev/video2"]

networks:
    fakecam:
